---
driver:
  name: ec2
  region: <%= ENV['AWS_REGION'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEYID'] %>
  iam_profile_name: AmazonEC2RoleforSSM
  # security_group_ids:
  #   - <%= ENV['AWS_SECURITY_GROUP_IDS'] %>

provisioner:
  name: local_shell

transport:
  ssh_key: <%= "#{ENV['HOME']}/.ssh/id_default" %>

platforms:
  - name: amazon-2016.09.1
    driver:
      image_id: ami-56d4ad31
      user_data: |
        #!/bin/bash
        curl -L https://omnitruck.chef.io/install.sh | sudo bash
        cd /tmp
        curl https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm -o amazon-ssm-agent.rpm
        yum install -y amazon-ssm-agent.rpm
    transport:
      username: ec2-user
suites:
  - name: linux-example
    provisioner:
      command: 'bundle exec rezept run_command -d Example-RunShellScript -i $KITCHEN_SERVER_ID --wait-results --wait-entries'
