#! /usr/bin/env ruby

PREFIX = ENV['REZEPT_ENV'] == 'test' ? 'Test-' : ''

Command "#{PREFIX}Example-RunShellScript" do
  account_ids []
  content do
    __dsl do
      schemaVersion "2.0"
      description "Run a shell script"
      mainSteps do |*|
        action "aws:runShellScript"
        name "runShellScript"
        inputs do
          runCommand __script(<<-'EOS')
echo example123 >> /tmp/result.txt
EOS
          TimeoutSeconds 10
        end
      end
    end
  end
end

Command "#{PREFIX}Example-RunPowerShellScript" do
  account_ids []
  content do
    __dsl do
      schemaVersion "2.0"
      description "Run a shell script"
      mainSteps do |*|
        action "aws:runPowerShellScript"
        name "runPowerShellScript"
        inputs do
          runCommand __script(<<-'EOS')
"example" >> C:\result.txt
EOS
          TimeoutSeconds 100
        end
      end
    end
  end
end
